<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Municipality select field</name>
   <tag></tag>
   <elementGuidId>7b094919-964f-49e6-9897-c229176853a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'BuildMunicipality' and (text() = '
        -- Välj --

            
                    Norrköping-Björkalund
                    Uppsala - Kumla trädgårdsgata
                    Varberg - Smeakalles äng
            

        
                Ale
                Alingsås
                Alvesta
                Arboga
                Arvika
                Askersund
                Avesta
                Bengtsfors
                Bjurholm
                Bjuv
                Boden
                Bollebygd
                Bollnäs
                Borgholm
                Borlänge
                Borås
                Botkyrka
                Boxholm
                Bromölla
                Bräcke
                Burlöv
                Båstad
                Dals-Ed
                Danderyd
                Degerfors
                Eda
                Ekerö
                Eksjö
                Emmaboda
                Enköping
                Eskilstuna
                Eslöv
                Essunga
                Fagersta
                Falkenberg
                Falköping
                Falun
                Filipstad
                Finspång
                Flen
                Forshaga
                Färgelanda
                Gagnef
                Gislaved
                Gnesta
                Gnosjö
                Gotland
                Grums
                Grästorp
                Gullspång
                Gävle
                Göteborg
                Götene
                Habo
                Hagfors
                Hallsberg
                Hallstahammar
                Halmstad
                Hammarö
                Haninge
                Heby
                Hedemora
                Helsingborg
                Herrljunga
                Hjo
                Hofors
                Huddinge
                Hudiksvall
                Hultsfred
                Hylte
                Håbo
                Hällefors
                Härnösand
                Härryda
                Hässleholm
                Höganäs
                Högsby
                Hörby
                Höör
                Järfälla
                Jönköping
                Kalmar
                Karlsborg
                Karlshamn
                Karlskoga
                Karlskrona
                Karlstad
                Katrineholm
                Kil
                Kinda
                Klippan
                Knivsta
                Kramfors
                Kristianstad
                Kristinehamn
                Kumla
                Kungsbacka
                Kungsör
                Kungälv
                Kävlinge
                Köping
                Laholm
                Landskrona
                Laxå
                Lekeberg
                Leksand
                Lerum
                Lessebo
                Lidingö
                Lidköping
                Lilla Edet
                Lindesberg
                Linköping
                Ljungby
                Ljusnarsberg
                Lomma
                Ludvika
                Luleå
                Lund
                Lycksele
                Lysekil
                Malmö
                Malung
                Mariestad
                Mark
                Markaryd
                Mellerud
                Mjölby
                Mora
                Motala
                Mullsjö
                Munkedal
                Munkfors
                Mölndal
                Mönsterås
                Mörbylånga
                Nacka
                Nora
                Norberg
                Nordmaling
                Norrköping
                Norrtälje
                Norsjö
                Nybro
                Nykvarn
                Nyköping
                Nynäshamn
                Nässjö
                Ockelbo
                Olofström
                Orust
                Osby
                Oskarshamn
                Ovanåker
                Oxelösund
                Partille
                Perstorp
                Piteå
                Ragunda
                Robertsfors
                Ronneby
                Rättvik
                Sala
                Salem
                Sandviken
                Sigtuna
                Simrishamn
                Sjöbo
                Skara
                Skellefteå
                Skinnskatteberg
                Skurup
                Skövde
                Smedjebacken
                Sollefteå
                Sollentuna
                Solna
                Sotenäs
                Staffanstorp
                Stenungsund
                Stockholm
                Storfors
                Strängnäs
                Strömstad
                Sundbyberg
                Sundsvall
                Sunne
                Surahammar
                Svalöv
                Svedala
                Svenljunga
                Säffle
                Säter
                Sävsjö
                Söderhamn
                Söderköping
                Södertälje
                Sölvesborg
                Tanum
                Tibro
                Tidaholm
                Tierp
                Timrå
                Tingsryd
                Tjörn
                Tomelilla
                Torsby
                Torsås
                Tranemo
                Tranås
                Trelleborg
                Trollhättan
                Trosa
                Tyresö
                Täby
                Töreboda
                Uddevalla
                Ulricehamn
                Umeå
                Upplands Väsby
                Upplands-Bro
                Uppsala
                Uppvidinge
                Vadstena
                Vaggeryd
                Valdemarsvik
                Vallentuna
                Vansbro
                Vara
                Varberg
                Vaxholm
                Vellinge
                Vetlanda
                Vimmerby
                Vindeln
                Vingåker
                Vårgårda
                Vänersborg
                Vännäs
                Värmdö
                Värnamo
                Västervik
                Västerås
                Växjö
                Ydre
                Ystad
                Åmål
                Ånge
                Årjäng
                Åsele
                Åstorp
                Åtvidaberg
                Älmhult
                Älvkarleby
                Ängelholm
                Öckerö
                Ödeshög
                Örebro
                Örkelljunga
                Örnsköldsvik
                Östersund
                Österåker
                Östhammar
                Östra Göinge
        
    ' or . = '
        -- Välj --

            
                    Norrköping-Björkalund
                    Uppsala - Kumla trädgårdsgata
                    Varberg - Smeakalles äng
            

        
                Ale
                Alingsås
                Alvesta
                Arboga
                Arvika
                Askersund
                Avesta
                Bengtsfors
                Bjurholm
                Bjuv
                Boden
                Bollebygd
                Bollnäs
                Borgholm
                Borlänge
                Borås
                Botkyrka
                Boxholm
                Bromölla
                Bräcke
                Burlöv
                Båstad
                Dals-Ed
                Danderyd
                Degerfors
                Eda
                Ekerö
                Eksjö
                Emmaboda
                Enköping
                Eskilstuna
                Eslöv
                Essunga
                Fagersta
                Falkenberg
                Falköping
                Falun
                Filipstad
                Finspång
                Flen
                Forshaga
                Färgelanda
                Gagnef
                Gislaved
                Gnesta
                Gnosjö
                Gotland
                Grums
                Grästorp
                Gullspång
                Gävle
                Göteborg
                Götene
                Habo
                Hagfors
                Hallsberg
                Hallstahammar
                Halmstad
                Hammarö
                Haninge
                Heby
                Hedemora
                Helsingborg
                Herrljunga
                Hjo
                Hofors
                Huddinge
                Hudiksvall
                Hultsfred
                Hylte
                Håbo
                Hällefors
                Härnösand
                Härryda
                Hässleholm
                Höganäs
                Högsby
                Hörby
                Höör
                Järfälla
                Jönköping
                Kalmar
                Karlsborg
                Karlshamn
                Karlskoga
                Karlskrona
                Karlstad
                Katrineholm
                Kil
                Kinda
                Klippan
                Knivsta
                Kramfors
                Kristianstad
                Kristinehamn
                Kumla
                Kungsbacka
                Kungsör
                Kungälv
                Kävlinge
                Köping
                Laholm
                Landskrona
                Laxå
                Lekeberg
                Leksand
                Lerum
                Lessebo
                Lidingö
                Lidköping
                Lilla Edet
                Lindesberg
                Linköping
                Ljungby
                Ljusnarsberg
                Lomma
                Ludvika
                Luleå
                Lund
                Lycksele
                Lysekil
                Malmö
                Malung
                Mariestad
                Mark
                Markaryd
                Mellerud
                Mjölby
                Mora
                Motala
                Mullsjö
                Munkedal
                Munkfors
                Mölndal
                Mönsterås
                Mörbylånga
                Nacka
                Nora
                Norberg
                Nordmaling
                Norrköping
                Norrtälje
                Norsjö
                Nybro
                Nykvarn
                Nyköping
                Nynäshamn
                Nässjö
                Ockelbo
                Olofström
                Orust
                Osby
                Oskarshamn
                Ovanåker
                Oxelösund
                Partille
                Perstorp
                Piteå
                Ragunda
                Robertsfors
                Ronneby
                Rättvik
                Sala
                Salem
                Sandviken
                Sigtuna
                Simrishamn
                Sjöbo
                Skara
                Skellefteå
                Skinnskatteberg
                Skurup
                Skövde
                Smedjebacken
                Sollefteå
                Sollentuna
                Solna
                Sotenäs
                Staffanstorp
                Stenungsund
                Stockholm
                Storfors
                Strängnäs
                Strömstad
                Sundbyberg
                Sundsvall
                Sunne
                Surahammar
                Svalöv
                Svedala
                Svenljunga
                Säffle
                Säter
                Sävsjö
                Söderhamn
                Söderköping
                Södertälje
                Sölvesborg
                Tanum
                Tibro
                Tidaholm
                Tierp
                Timrå
                Tingsryd
                Tjörn
                Tomelilla
                Torsby
                Torsås
                Tranemo
                Tranås
                Trelleborg
                Trollhättan
                Trosa
                Tyresö
                Täby
                Töreboda
                Uddevalla
                Ulricehamn
                Umeå
                Upplands Väsby
                Upplands-Bro
                Uppsala
                Uppvidinge
                Vadstena
                Vaggeryd
                Valdemarsvik
                Vallentuna
                Vansbro
                Vara
                Varberg
                Vaxholm
                Vellinge
                Vetlanda
                Vimmerby
                Vindeln
                Vingåker
                Vårgårda
                Vänersborg
                Vännäs
                Värmdö
                Värnamo
                Västervik
                Västerås
                Växjö
                Ydre
                Ystad
                Åmål
                Ånge
                Årjäng
                Åsele
                Åstorp
                Åtvidaberg
                Älmhult
                Älvkarleby
                Ängelholm
                Öckerö
                Ödeshög
                Örebro
                Örkelljunga
                Örnsköldsvik
                Östersund
                Österåker
                Östhammar
                Östra Göinge
        
    ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@data-required-text='Du behöver välja kommun/område för att fortsätta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BuildMunicipality</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ahus.startOptions.configure(this, $(this).closest('form'))</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-title</name>
      <type>Main</type>
      <value>Ursäkta att vi stör</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required-text</name>
      <type>Main</type>
      <value>Du behöver välja kommun/område för att fortsätta</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        -- Välj --

            
                    Norrköping-Björkalund
                    Uppsala - Kumla trädgårdsgata
                    Varberg - Smeakalles äng
            

        
                Ale
                Alingsås
                Alvesta
                Arboga
                Arvika
                Askersund
                Avesta
                Bengtsfors
                Bjurholm
                Bjuv
                Boden
                Bollebygd
                Bollnäs
                Borgholm
                Borlänge
                Borås
                Botkyrka
                Boxholm
                Bromölla
                Bräcke
                Burlöv
                Båstad
                Dals-Ed
                Danderyd
                Degerfors
                Eda
                Ekerö
                Eksjö
                Emmaboda
                Enköping
                Eskilstuna
                Eslöv
                Essunga
                Fagersta
                Falkenberg
                Falköping
                Falun
                Filipstad
                Finspång
                Flen
                Forshaga
                Färgelanda
                Gagnef
                Gislaved
                Gnesta
                Gnosjö
                Gotland
                Grums
                Grästorp
                Gullspång
                Gävle
                Göteborg
                Götene
                Habo
                Hagfors
                Hallsberg
                Hallstahammar
                Halmstad
                Hammarö
                Haninge
                Heby
                Hedemora
                Helsingborg
                Herrljunga
                Hjo
                Hofors
                Huddinge
                Hudiksvall
                Hultsfred
                Hylte
                Håbo
                Hällefors
                Härnösand
                Härryda
                Hässleholm
                Höganäs
                Högsby
                Hörby
                Höör
                Järfälla
                Jönköping
                Kalmar
                Karlsborg
                Karlshamn
                Karlskoga
                Karlskrona
                Karlstad
                Katrineholm
                Kil
                Kinda
                Klippan
                Knivsta
                Kramfors
                Kristianstad
                Kristinehamn
                Kumla
                Kungsbacka
                Kungsör
                Kungälv
                Kävlinge
                Köping
                Laholm
                Landskrona
                Laxå
                Lekeberg
                Leksand
                Lerum
                Lessebo
                Lidingö
                Lidköping
                Lilla Edet
                Lindesberg
                Linköping
                Ljungby
                Ljusnarsberg
                Lomma
                Ludvika
                Luleå
                Lund
                Lycksele
                Lysekil
                Malmö
                Malung
                Mariestad
                Mark
                Markaryd
                Mellerud
                Mjölby
                Mora
                Motala
                Mullsjö
                Munkedal
                Munkfors
                Mölndal
                Mönsterås
                Mörbylånga
                Nacka
                Nora
                Norberg
                Nordmaling
                Norrköping
                Norrtälje
                Norsjö
                Nybro
                Nykvarn
                Nyköping
                Nynäshamn
                Nässjö
                Ockelbo
                Olofström
                Orust
                Osby
                Oskarshamn
                Ovanåker
                Oxelösund
                Partille
                Perstorp
                Piteå
                Ragunda
                Robertsfors
                Ronneby
                Rättvik
                Sala
                Salem
                Sandviken
                Sigtuna
                Simrishamn
                Sjöbo
                Skara
                Skellefteå
                Skinnskatteberg
                Skurup
                Skövde
                Smedjebacken
                Sollefteå
                Sollentuna
                Solna
                Sotenäs
                Staffanstorp
                Stenungsund
                Stockholm
                Storfors
                Strängnäs
                Strömstad
                Sundbyberg
                Sundsvall
                Sunne
                Surahammar
                Svalöv
                Svedala
                Svenljunga
                Säffle
                Säter
                Sävsjö
                Söderhamn
                Söderköping
                Södertälje
                Sölvesborg
                Tanum
                Tibro
                Tidaholm
                Tierp
                Timrå
                Tingsryd
                Tjörn
                Tomelilla
                Torsby
                Torsås
                Tranemo
                Tranås
                Trelleborg
                Trollhättan
                Trosa
                Tyresö
                Täby
                Töreboda
                Uddevalla
                Ulricehamn
                Umeå
                Upplands Väsby
                Upplands-Bro
                Uppsala
                Uppvidinge
                Vadstena
                Vaggeryd
                Valdemarsvik
                Vallentuna
                Vansbro
                Vara
                Varberg
                Vaxholm
                Vellinge
                Vetlanda
                Vimmerby
                Vindeln
                Vingåker
                Vårgårda
                Vänersborg
                Vännäs
                Värmdö
                Värnamo
                Västervik
                Västerås
                Växjö
                Ydre
                Ystad
                Åmål
                Ånge
                Årjäng
                Åsele
                Åstorp
                Åtvidaberg
                Älmhult
                Älvkarleby
                Ängelholm
                Öckerö
                Ödeshög
                Örebro
                Örkelljunga
                Örnsköldsvik
                Östersund
                Österåker
                Östhammar
                Östra Göinge
        
    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;site&quot;]/div[@class=&quot;site-content&quot;]/main[@class=&quot;main-content main-content--wide&quot;]/div[@class=&quot;startpage-container&quot;]/article[@class=&quot;article&quot;]/div[@class=&quot;startpage-content content-holder&quot;]/div[@class=&quot;start-options-block a-block&quot;]/div[2]/div[@class=&quot;select-area-box&quot;]/form[1]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
