<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Epostadress</name>
   <tag></tag>
   <elementGuidId>8824dd08-506c-4558-9d3e-14d6eaee6c3e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>derome-formitem__header</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Epostadress
                            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;site&quot;]/div[@class=&quot;site-content&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;main-content__inner&quot;]/div[@class=&quot;p-infopage&quot;]/div[@class=&quot;p-infopage__content&quot;]/div[@class=&quot;block-list&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;infoblock infoblock--extra-padding&quot;]/form[@class=&quot;js-account-form&quot;]/div[@class=&quot;js-content-switch&quot;]/div[@class=&quot;infoblock__content&quot;]/div[@class=&quot;derome-formitem&quot;]/div[@class=&quot;derome-formitem__header&quot;]</value>
   </webElementProperties>
</WebElementEntity>
